### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by giswqs** [cholmes/google-buildings-tools#1]
Great work on the project! It would be great to create a python package for this and publish it on PyPI. 
Here is a Python package template I use for my open-source projects. It is very easy to use. I can help create it and transfer the package ownership to you. You are also welcome to try it out on your own.
https://github.com/giswqs/pypackage

What package name do you like?

**Comment by cholmes** [comment]
Awesome! Yeah, publishing on PyPI is an eventual goal, but not even being able to get to `pip install .` got me discouraged on reaching that. But this looks great. I'd be happy for you to create it and transfer ownership, and then try it on my own for a next one. 

I'm not sure on package name - any advice? Like in the python world are good names super descriptive? Or acronyms of descriptive things? Or just try to be memorable? I think my ideas are like:

google-buildings-tools (match the repo name, though I don't really know how it'd evolve)
gob-tools (shorter name, acronym for google open buildings)
open-building-tools or ob-tools (leave space to also add tools to work with microsoft open buildings / osm)

Does it make sense to try to name the package the same as the CLI command that it'll install? I know rasterio / fiona don't - that precedent seems to be to make a super short cli command. 

I guess the other thing I'd love advice on is scope for repos / packages. Like there's a number of semi-related things I want to work on:
* tools to make google buildings better (remove multi polygons, add country and admin 1 attributes, partition geoparquet, make PMTiles (wrap tippecanoe with some 'opinion', split up big fgbs or figure out gdal/ogr interface for tippecanoe to work with geoparquet), and also get it into iceberg/delta lake.
* Tools to benchmark working with different tools / formats - like add country / admin 1 with postgis vs duckdb vs bigquery vs sedona, or repartition & partition spatially, or iceberg vs delta lake, and also just do generic benchmarking of format translations (like not be specific to the building csv's like it is today).
* potentially tools to work with microsoft buildings, though planetary computer is already distributing in partitioned geoparquet, so a lot less to do here. 
* potentially tools to compare and/or combine microsoft and google buildings. Or other approaches.

So like should I just make one repo and one package? Or lots of little tools? I guess my question even extends to the code - should I just keep building in one file, with lots of different functionality? Do one file per 'function' in a CLI that has lots of different 'tools' in it? Or make independent tools that maybe work in concert.

No worries if you don't have strong opinions - I can just make a call and evolve. Just mostly looking for any precedents in the python world, if things will make more sense to people if I do it one way or another.

**Comment by giswqs** [comment]
I would suggest the name `open-buildings`. It is short, descriptive, and expandable. You can have tools for google, microsoft, osm, all in the same package. You don't need the `cli` in the name as the package would contain functionality for both cli and python scripting. 

I would suggest putting all tools in one repo at the moment, which is easier the build the momentum and gain stars. If it grows too big and have too many functionality, you can consider spin off some of the tool to form new packages.

**Comment by giswqs** [comment]
Here it is. I have added you as admin for the repo. Check your email. Feel free to play with it and transfer to your account. Note that you will be need to enable GitHub Pages and add PyPI access tokens if you want to enable automated release to PyPI. 

GitHub: https://github.com/opengeos/open-buildings
Docs: https://opengeos.github.io/open-buildings
PyPI: https://pypi.org/project/open-buildings

```bash
pip install open-buildings
```

**Comment by cholmes** [comment]
Sweet! I'm also totally happy to just keep it in opengeos if you think that makes sense? I can just close this repo and collaborate there.

**Comment by cholmes** [comment]
And tried it out, looks like it mostly worked - so cool! 

```
% pip install open-buildings
Collecting open-buildings
  Downloading open_buildings-0.0.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: click in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (8.1.3)
Requirement already satisfied: duckdb in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (0.8.1)
Requirement already satisfied: pandas in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (2.0.1)
Requirement already satisfied: geopandas in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (0.13.0)
Requirement already satisfied: shapely in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (2.0.1)
Requirement already satisfied: openlocationcode in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (1.0.1)
Requirement already satisfied: tabulate in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from open-buildings) (0.9.0)
Requirement already satisfied: fiona>=1.8.19 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from geopandas->open-buildings) (1.9.3)
Requirement already satisfied: packaging in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from geopandas->open-buildings) (23.1)
Requirement already satisfied: pyproj>=3.0.1 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from geopandas->open-buildings) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from pandas->open-buildings) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from pandas->open-buildings) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from pandas->open-buildings) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from pandas->open-buildings) (1.24.3)
Requirement already satisfied: attrs>=19.2.0 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from fiona>=1.8.19->geopandas->open-buildings) (23.1.0)
Requirement already satisfied: certifi in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from fiona>=1.8.19->geopandas->open-buildings) (2023.5.7)
Requirement already satisfied: click-plugins>=1.0 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from fiona>=1.8.19->geopandas->open-buildings) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from fiona>=1.8.19->geopandas->open-buildings) (0.7.2)
Requirement already satisfied: munch>=2.3.2 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from fiona>=1.8.19->geopandas->open-buildings) (3.0.0)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniforge/base/envs/qgis/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->open-buildings) (1.16.0)
Installing collected packages: open-buildings
Successfully installed open-buildings-0.0.2
(qgis) cholmes@Chriss-MBP google-buildings-tools % open-buildings
zsh: command not found: open-buildings
(qgis) cholmes@Chriss-MBP google-buildings-tools % open_buildings
Replace this message by putting your code into open_buildings.cli.main
See click documentation at https://click.palletsprojects.com/
(qgis) cholmes@Chriss-MBP google-buildings-tools %  
```    

Any insight on the change needed for it to work? This is further than I got, but tweaking this type of thing is what got me into a mess.

Also seems like we should have the package name be the same as the cli, instead of really close? open-buildings vs open_buildings

**Comment by giswqs** [comment]
Sure. opengeos would be happy to host it. For now, all the functions you added should be accessible now. I will look into the CLI and add some notebook examples. Feel free to add anything you like. I will improve it if any.

**Comment by cholmes** [comment]
Closing this issue in favor of https://github.com/opengeos/open-buildings/issues/2
